### ISSUE TITLE
Missing ward in the mid?

### ISSUE THREAD

**Issue by y-sheng** [answerquest/pune-2022-wards#1]
Hi.

Many thanks for this incredible data.
I have tried to input the data into ArcGIS and found a bit is missing in the centre of the city, please see a snapshot attached below.  
![image](https://github.com/answerquest/pune-2022-wards/assets/61703892/e6e5cb50-27a4-448b-be9b-306193481462)
This seems to be the '20 Pune Station -Matoshri Ramabai Ambedkar Road' as stated in the ward-attributes csv provided. Is there any reason this is not included in the map? 

Best regards

**Comment by nikhil-scholarlify** [comment]
@y-sheng that's military area, it's governed by  Pune Cantonment Board. The Pune Municipal Corporation doesn't have jurisdiction there. Those areas have always been cantonment; you can see previous years' shapes at https://github.com/datameet/Municipal_Spatial_Data/tree/master/Pune
